import type { Metadata } from 'next';
import './globals.css';
import Providers from './providers';
import { Toaster } from '@/components/ui/sonner';
export const metadata: Metadata = {
  title: 'CribCloud',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.svg',
  },
};
import { Inter, Poppins } from 'next/font/google';
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: ['300', '400', '600', '700', '800'],
});
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  variable: '--font-display',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <body>
        <Providers>{children}</Providers>
        <Toaster closeButton />
      </body>
    </html>
  );
}
